Bot api branch
U2-LABS/bot-telegram-poll-disco pull request #1
Opened 2020-10-22 14:22 UTC by NikDark

Готовый бот с REST API
Мы знаем про ТОКЕНЫ, но просто потом нужно все равно пересоздать эти боты и токены поменяются
И сразу извиняемся за отстойный подбор музыки, это все делается рандомно)

2020-10-30 12:24 UTC, shurph requested changes

2020-10-30 12:24 UTC, shurph commented on bot/work_with_csv.py
> +            if idx == 0:  # first line is headers
уверены? )

2020-10-30 12:24 UTC, shurph commented on bot/config_class.py
> +        self.filename = os.getenv("MUSIC_FILE")
здесь можно дать дефолтное значение для переменной для тех случаев, когда в переменных окружения не задана соотвутсвующая опция

2020-10-30 12:24 UTC, shurph commented on bot/config_class.py
> +            os.getenv("SAVED_JSON")
здесь можно дать дефолтное значение для переменной для тех случаев, когда в переменных окружения не задана соотвутсвующая опция

2020-10-30 12:24 UTC, shurph commented on bot/config_class.py
> +            else os.getenv("DEFAULT_JSON")
здесь можно дать дефолтное значение для переменной для тех случаев, когда в переменных окружения не задана соотвутсвующая опция

2020-10-30 12:24 UTC, shurph commented on bot/config_class.py
> +            if os.path.exists(os.getenv("SAVED_JSON"))
а вообще было бы неплохо как-то самостоятельно находить последний созранённый конфиг в текущей дериктории (ну или в указанной пользователем директории)

2020-10-30 12:24 UTC, shurph commented on bot/config_class.py
> +            config = json.load(r_file)
всё-таки посмотрите в сторону marshmallow. просто взять json и работать с ним можно, но это довольно спорный подход.

опять же, дальше вы используете этот json как dict, в котором ключи в camelCase формате.
а в питоне всё-таки как-то принято с snake_case работать

посмотрите вот на эти вещи:
- https://github.com/okunishinishi/python-stringcase
- https://marshmallow.readthedocs.io/en/latest/examples.html#inflection-camel-casing-keys

2020-10-30 12:24 UTC, shurph commented on bot/handlers.py
> +def started_pool(func):
повыносить бы декораторы в отдельный файл

2020-11-06 18:16 UTC, misterw commented on bot_top_ranking/decorators.py
> +    get_state.bot = bot
Для чего нужна такая реализация? На этапе компиляции мы раз 8 присваиваем ссылку на эти объекты при декорировании. Можно ли напрямую обращаться к объектам state и  bot при необходимости, если вынести их, к примеру, в utils.py?

2020-11-07 10:22 UTC, misterw commented on bot_top_ranking/__main__.py
> +        bot.polling(none_stop=True)
Первый раз мы создаем state объект, когда импортируем bot. Т.к. у нас синглтон - второй раз мы повторно его инициализируем в 5-й строке. Зачем? Импортировав state, мы избавляемся от повторной инициализации, что экономит время исполнения и убираем строку импорта.

2020-11-07 11:04 UTC, JuliusChrona commented on bot_top_ranking/__main__.py
> +        bot.polling(none_stop=True)
Не думал, что уже созданный экземпляр можно использовать как контекстный менеджер. Теперь буду знать, спасибо.
Уже исправлено ^_^

2020-11-07 11:21 UTC, JuliusChrona commented on bot_top_ranking/decorators.py
> +    get_state.bot = bot
До этого была проблема с круговым импортом, но думаю если вынести в отдельный файл, проблем быть не должно; сейчас пойду попробую.

2020-11-07 12:24 UTC, JuliusChrona commented on bot_top_ranking/decorators.py
> +    get_state.bot = bot
Всё прекрасно работает, апдейт залит :)

2020-11-09 09:44 UTC, misterw commented on bot_top_ranking/decorators.py
> +    get_state.bot = bot
Можно использовать локальные импорты, внутри функции. Их обычно и используют в случае зацикливания, или при наличии такой вероятности.

2020-11-09 10:27 UTC, misterw commented on bot_top_ranking/__main__.py
> +        bot.polling(none_stop=True)
У with определенные инструкции, начать с '__enter__', закончить '__exit__', экземпляр всегда создается до выполнения with , а где именно - тут скорее зависит от  логики. В данном случае лучше передавать готовый, а не дергать State().

2020-11-10 12:31 UTC, JuliusChrona commented on bot/handlers.py
> +def started_pool(func):
Декораторы были вынесены в отдельный файл decorators.py

2020-11-10 12:33 UTC, JuliusChrona commented on bot/config_class.py
> +            config = json.load(r_file)
json теперь переводится в dict, в котором все ключи в snake_case.
Marshmallow schema находится в файле "marsh_schemas.py"

2020-11-10 12:34 UTC, JuliusChrona commented on bot/config_class.py
> +            if os.path.exists(os.getenv("SAVED_JSON"))
Добавили файл .env.example и написали readme, в ней сказаны все переменные, которые надо установить

2020-11-10 12:35 UTC, JuliusChrona commented on bot/work_with_csv.py
> +            if idx == 0:  # first line is headers
Удалили данную проверку, была лишняя ^_^

2020-11-10 12:36 UTC, JuliusChrona commented on bot/config_class.py
> +        self.filename = os.getenv("MUSIC_FILE")
Добавили файл .env.example и написали readme, в ней сказаны все переменные, которые надо установить

2020-11-10 12:36 UTC, JuliusChrona commented on bot/config_class.py
> +            else os.getenv("DEFAULT_JSON")
Добавили файл .env.example и написали readme, в ней сказаны все переменные, которые надо установить

2020-11-10 12:37 UTC, JuliusChrona commented on bot.py
> +    if check_admin_permissions(message):
Был создан декоратор для этой проверки и помещён в файл decorators.py

2020-11-10 12:39 UTC, JuliusChrona commented on bot.py
> +            for index, vote in enumerate(setup.voted_users):
Данный код был заменён на более понятный
```Python
if state.config["upload_flag"]:
    upload_song(top_list[idx], bot, state)
else:
    bot_reply_message = f'{top_list[idx]["author"]} | {top_list[idx]["title"]}'
    bot.send_message(state.config["chat_id"], bot_reply_message)
song_index = top_list[idx]["pos"] - 1  # positions of songs starts by 1
song_item = state.config["songs"][song_index]
song_item["voted_users"] = []
song_item["mark"] = 0
state.config["songs"][song_index] = song_item
```

2020-11-10 12:42 UTC, JuliusChrona commented on bot.py
> +            top_list.sort(key=lambda song: song["mark"], reverse=True)
При инстанцировании объекта State происходит создание списка песен, и его сортировка по `title`. В местах где надо получить список топ-песен, вызывается функция сортировки дополнительно по `mark`

2020-11-10 12:43 UTC, JuliusChrona commented on bot.py
> +            download_music_link(top_list[idx].link)
Был добавлена команда `/settings_mp3`, которая отвечает за переключение режима

2020-11-10 12:43 UTC, JuliusChrona commented on bot.py
> +            bot.send_audio(message.chat.id, audio)
Был добавлена команда `/settings_mp3`, которая отвечает за переключение режима

2020-11-10 12:45 UTC, JuliusChrona commented on bot.py
> +            top_list = setup.songs.copy()
Была созданна функция для сортировки
```Python
def create_top(songs):
    top_list = sorted(songs, key=lambda song: song["mark"], reverse=True)
    return top_list
```

2020-11-10 12:46 UTC, JuliusChrona commented on bot.py
> +    top_list = setup.songs.copy()
Была созданна функция для сортировки
```Python
def create_top(songs):
    top_list = sorted(songs, key=lambda song: song["mark"], reverse=True)
    return top_list
```

2020-11-10 12:47 UTC, JuliusChrona commented on bot.py
> +    else:
Негативные ветки были перенесены вверх

2020-11-10 12:47 UTC, JuliusChrona commented on bot.py
> +        setup.make_default_setup()
`setup` была переименована в `state`

2020-11-10 12:48 UTC, JuliusChrona commented on bot.py
> +        bot.send_message(setup.chat_id, "Pool hasn't started yet. Type /poll to start")
Упс, опечатка исправлена

2020-11-10 12:48 UTC, NikDark commented on bot.py
> +        top_number = int(re.search(r'^/top ([\d]*)$', message.text).group(1))
Здесь нужна регулярка, так как пользователь может ввести следующее
```/top 1 2 3``` и это будет как ошибка

2020-11-10 12:48 UTC, JuliusChrona commented on bot.py
> +        music_pool = ''
Понимаем, наш переводчик получит за это :)

2020-11-10 12:49 UTC, JuliusChrona commented on bot.py
> +def create_pool(message):
Переводчик сильно раскаивается

2020-11-10 12:50 UTC, JuliusChrona commented on bot.py
> +def music_from_csv(path_csv : str) -> dict:
функции перенесены в отдельные файлы `work_with_csv.py` и `help_functions.py`

2020-11-10 12:50 UTC, JuliusChrona commented on bot.py
> +setup = Setup()
`setup` была переименована в `state`

2020-11-10 12:51 UTC, JuliusChrona commented on bot.py
> +        setup.current_idx -= setup.count_rows
Добавили передачу bot и state, в функции используемые в боте не как хэндлеры

2020-11-10 12:52 UTC, JuliusChrona commented on bot.py
> +    temp = setup.count_rows
Создан синглтон-класс State

2020-11-10 12:53 UTC, JuliusChrona commented on bot.py
> +        self.songs = get_music_csv("nikita.csv")
Вшитые имена заменены на environment variables

2020-11-10 12:53 UTC, JuliusChrona commented on bot.py
> +        self.users_for_promoting = self.config['usersForPromoting']
json теперь переводится в dict, в котором все ключи в snake_case.
Marshmallow schema находится в файле `marsh_schemas.py`

2020-11-10 12:54 UTC, JuliusChrona commented on bot.py
> +            self.config = json.load(r_file)
Больше не складываем значения в отдельные переменные, берём их напрямую из config

2020-11-10 12:55 UTC, JuliusChrona commented on work_music.py
> +    response = requests.get(ZAYCEV_URL)
Это была тестовая строка, забыли удалить.
`Удалена`

2020-11-10 12:55 UTC, JuliusChrona commented on work_music.py
> +create_csv("nikita.csv")
Это была тестовая строка, забыли удалить.
`Удалена`

2020-11-10 12:56 UTC, JuliusChrona commented on bot.py
> +    return ''.join((list(map(lambda digit: NUMBERS[int(digit)], str(number)))))
Полностью согласен, `list` был лишним.
Функция была удалена из-за ненадобности.

2020-11-10 12:57 UTC, JuliusChrona commented on work_music.py
> +        song['link'] = 'https://zaycev.net' + song_a.get('href')
Использует теперь переменную

2020-11-10 12:58 UTC, JuliusChrona commented on work_music.py
> +        song['link'] = 'https://zaycev.net' + song_a.get('href')
Используем теперь переменную

2020-11-10 12:58 UTC, JuliusChrona commented on bot.py
> +NINE = '\U00000039\U000020E3'
Удалены из-за ненадобности

2020-11-10 12:58 UTC, JuliusChrona commented on requirements.txt
> +asgiref==3.2.10
Зависимости были обновлены

2020-11-15 23:28 UTC, shurph approved these changes

2020-11-15 23:28 UTC, merged